### ISSUE TITLE
04-Linked-List中toString方法存在错误

### ISSUE THREAD

**Issue by Chiaki-xps** [biaodigit/Play-with-Data-Structures#2]
`
toString() {
            let ret = '',
                cur = this.dummyHead.next;
            while (cur) {
                ret += `${cur}->`;
                cur = cur.next
            }
            ret += 'null';
            return ret
        }
`
中ret += `${cur}->`;应当改为ret += `${cur.e}->`;

抛出异常的描述可以改一下，全部都是Add failed。

**Comment by biaodigit** [comment]
#3 已合并，感谢更正🙏
